7.2_eventbrite_clone_step2/config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  devise_for :users
  resources :attendances
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

7.2_eventbrite_clone_step2/app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :participation_send

  belongs_to :user
  belongs_to :event

  def participation_send
    UserMailer.participation_email(self).deliver_now
  end
end

7.2_eventbrite_clone_step2/app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, :duration, :title, :description, :price, :location, presence: true
  validates :title, length: {minimum: 5, maximum: 140}
  validates :description, length: {minimum: 20, maximum: 1000}
  validates :price, numericality: {greater_than: 0, less_than_or_equal_to: 1000}
  validate :multiple_of_five
  validate :cant_be_zero
  validate :cant_be_past
  belongs_to :admin, class_name: 'User'
  has_many :attendances
  has_many :users, through: :attendances


  def end_date
    self.start_date + (self.duration * 60)
  end

private 

  def multiple_of_five
    errors.add(:duration, "has to be a multiple of 5") unless duration % 5 == 0 
  end

  def cant_be_zero
    errors.add(:duration, "can't be 0") if duration == 0
  end

  def cant_be_past
    errors.add(:start_date, "can't be past") if start_date < Time.now
  end

end

7.2_eventbrite_clone_step2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :events, foreign_key: 'admin_id', class_name: 'Event'
  has_many :attendances
  has_many :events, through: :attendances

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

7.2_eventbrite_clone_step2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation, :current_password)}
  end
end

7.2_eventbrite_clone_step2/app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.fetch(:attendance, {})
    end
end

7.2_eventbrite_clone_step2/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @admin = User.find(@event.admin_id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :admin_id)
    end
end

7.2_eventbrite_clone_step2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    redirect_to :root
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to '/users/edit'
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :encrypted_password, :description, :first_name, :last_name)
    end
end

7.2_eventbrite_clone_step2/app/helpers/attendances_helper.rb
module AttendancesHelper
end

7.2_eventbrite_clone_step2/app/helpers/events_helper.rb
module EventsHelper
end

7.2_eventbrite_clone_step2/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

7.2_eventbrite_clone_step2/app/helpers/users_helper.rb
module UsersHelper
end

7.2_eventbrite_clone_step2/app/views/events/_form.html.erb
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :start_date %>
      <%= form.datetime_select :start_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :duration %>
      <%= form.range_field :duration, within: 0..120, step: 5, oninput:"updateTextInput(this.value)", id:"inputRange", class:"form-control" %>
      <%= form.number_field :fake, within: 5..120, value: 60, id: "textInput", oninput: "updateRangeInput(this.value)"%>
    </div>


    <div class="form-group">
      <%= form.label :price %>
      <%= form.number_field :price, within: 1..1000, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :location %>
      <%= form.text_field :location, class: "form-control" %>
    </div>

    <%= form.hidden_field :admin_id, value: current_user.id %>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<script>
function updateTextInput(val) {
          document.getElementById('textInput').value=val; 
        }
function updateRangeInput(val) {
  document.getElementById('inputRange').value=val; 
}
</script>

<br><br>

7.2_eventbrite_clone_step2/app/views/events/edit.html.erb
<main class="container">
<h1 class="text-center">Editer votre évènement</h1>

<%= render 'form', event: @event %>

<div class="text-center">
<%= link_to "Voir l'évènement", @event, class:"btn btn-info" %> |
<%= link_to '« Retour Accueil', events_path, class:"btn btn-primary" %>
</div>
</main>

7.2_eventbrite_clone_step2/app/views/events/index.html.erb
<div class="jumbotron" 
  style="background-image: url(https://images.pexels.com/photos/1157557/pexels-photo-1157557.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;">
  <div class="container" style="background-color: rgba(255, 255, 255, 0.6); padding: 25px; border-radius: 20px;">
    <h1 class="display-3">Eventbrite</h1>
    <p>Retrouvez tous les évènements près de chez vous et partagez les vôtres</p>
    <p><%= link_to 'Créer un évènement »', new_event_path, class:"btn btn-primary btn-lg" %></p>
  </div>
</div>
<p id="notice"><%= notice %></p>
  
<main class="container">
<h1 class="d-flex justify-content-center">Liste des évènements à venir</h1>

<% @events.each do |event| %>

<div class="card my-3">
  <div class="card-header">
    <h4><%= event.title %></h4>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= event.start_date.strftime("%A, %d/%m/%Y") %> à <%= event.location %></h5>
    <p class="card-text"><%= event.description %></p>
    <%= link_to 'Voir +', event, class:"btn btn-primary" %> 
    <% if user_signed_in? && current_user.id == event.admin.id %>
    <%= link_to 'Editer', edit_event_path(event), class:"btn btn-success" %> 
    <%= link_to 'Supprimer', event, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    <% end %>
  </div>
  <div class="card-footer">
    Prix : <%= event.price %> € // Durée : <%= event.duration %> min
  </div>
</div>

<% end %>

</main>

7.2_eventbrite_clone_step2/app/views/events/new.html.erb
<main class="container">
  
<h1 class="text-center">Création d'un nouvel évènement</h1>

<%= render 'form', event: @event %>

<%= link_to '« Retour Accueil', events_path, class:"btn btn-primary" %>
  
</main>

7.2_eventbrite_clone_step2/app/views/events/show.html.erb
<main class="container">
<p id="notice"><%= notice %></p>

<h1 class="text-center"><%= @event.title %></h1>


<div class="card my-5">
  <div class="card-header">
      <strong>Email de l'organisateur : </strong><%= @admin.email %>
  <!--  <%= link_to 'Voir profil', user_path(@admin.id) %>  sortir également la première ligne de la methode show dans le controleur-->
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><strong>Début : </strong><%= @event.start_date.strftime('%d/%m/%Y à %H:%M') %></li>
    <li class="list-group-item"><strong>Fin : </strong><%= @event.end_date.strftime('%d/%m/%Y à %H:%M') %></li>
    <li class="list-group-item"><strong>Prix : </strong><%= @event.price %> €</li>
    <li class="list-group-item"><strong>Où : </strong><%= @event.location %></li>
    <li class="list-group-item"><strong>Description : </strong><%= @event.description %></li>
  </ul>
</div>

<% if user_signed_in? && current_user.id == @admin.id %>
<%= link_to 'Editer', edit_event_path(@event), class:"btn btn-success" %> 
<%= link_to 'Supprimer', @event, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<% end %>

<%= link_to '« Retour Accueil', events_path, class:"btn btn-primary" %>
</main>