fin_10_e-commerce_chatons/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "items#index"
  devise_for :users
  resources :items, path: 'photo_de_chat' do 
    resources :rating, only: [:update]
    resources :comments, only: [:create, :edit, :update, :destroy], path: 'mon_commentaire'
  end
  resources :carts, only: [:show, :update, :destroy], path: 'mon_panier'
  resources :users, only: [:show, :update, :edit], path: 'mon_profil'
  resources :charges, only: [:new, :create], path: 'paiement'

  scope 'admin', module: 'admin', as: 'admin' do
    resources :dashboard, only: [:index]
    resources :users
    resources :orders
    resources :items
  end
end

fin_10_e-commerce_chatons/app/models/item.rb
class Item < ApplicationRecord

  validates :title, 
    presence: true,
    length: { in: 3..50 }
  validates :description,
    length: { maximum: 1024 }
  validates :price,
    numericality: { greater_than: 0 }

  has_one_attached :picture

  validates :picture, 
    presence: true

  belongs_to :category

  has_many :join_cart_items
  has_many :carts, through: :join_cart_items

  has_many :join_order_items
  has_many :orders, through: :join_order_items

  has_many :comments
  has_many :users, through: :comments

  has_many :rating

  def join_id(user)
    self.join_cart_items.where(cart: user.cart.id)
  end

  def quantity(id)
    self.join_cart_items.find_by(cart_id:id).quantity
  end
  
  def item_average_rating
    unless self.rating.count == 0
      self.rating.pluck(:rating).sum / self.rating.count
    end
  end

  def item_star(star = 0)
    if star == 0
      self.rating.count
    else
      self.rating.where(rating: star).count
    end
  end

  def percent(num)
    self.item_star(num).to_f / self.item_star * 100
  end
end

fin_10_e-commerce_chatons/app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController
  before_action :set_admin_item, only: [:show, :edit, :update, :destroy]

  # GET /admin/items
  # GET /admin/items.json
  def index
    @admin_items = Item.all
  end

  # GET /admin/items/1
  # GET /admin/items/1.json
  def show
    @comment = Comment.new
    @comments = @admin_item.comments
  end

  # GET /admin/items/new
  def new
    @admin_item = Item.new
  end

  # GET /admin/items/1/edit
  def edit
  end

  # POST /admin/items
  # POST /admin/items.json
  def create
    @admin_item = Item.new(admin_item_params)

    respond_to do |format|
      if @admin_item.save
        format.html { redirect_to @admin_item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @admin_item }
      else
        format.html { render :new }
        format.json { render json: @admin_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/items/1
  # PATCH/PUT /admin/items/1.json
  def update
    respond_to do |format|
      if @admin_item.update(admin_item_params)
        format.html { redirect_to @admin_item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_item }
      else
        format.html { render :edit }
        format.json { render json: @admin_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/items/1
  # DELETE /admin/items/1.json
  def destroy
    @admin_item.destroy
    respond_to do |format|
      format.html { redirect_to admin_items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_item
      @admin_item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_item_params
      params.fetch(:admin_item, {})
    end
end

fin_10_e-commerce_chatons/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.includes(:category).all
    @categories = Category.all
  end
  
  def show
    @item = Item.find(params[:id])
    @comment = Comment.new
    @comments = @item.comments
    
    if current_user
      find = Rating.find_by(user_id: current_user.id , item_id: params[:id])
    end
  
    if find == nil
      @rate = 0
    else
      @rate = find.rating
    end
  end

  def destroy
    item = Item.find(params[:id])
    JoinCartItem.find_by(cart_id: @cart.id, item_id: item.id).destroy
    respond_to do |format|
      format.js  
    end
  end
end

fin_10_e-commerce_chatons/app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

fin_10_e-commerce_chatons/app/helpers/items_helper.rb
module ItemsHelper
end

fin_10_e-commerce_chatons/app/views/items/_add_cart.html.erb
<% if !@cart.is_in_cart?(params[:id]) %>
<div class="form-inline">
<%= form_with method: "PUT", url: cart_path  do |form| %>
  <%= form.number_field :quantity , min: 1, value: 1, class: "form-control w-25"%>
  <%= form.submit "Ajouter au panier".html_safe, class:"btn btn-success"%>
<% end %>
</div>

<% else %>
<div class="form-inline">
<%= form_with method: "PUT", url: cart_path  do |form| %>
  <%= form.number_field :quantity , value: @cart.is_in_cart?(params[:id]).quantity , class:"form-control w-25"%>
  <%= form.submit "Modifier la quantité ".html_safe, class:"btn btn-success "%>
  <%= link_to "<i class='fa fa-trash'></i>".html_safe, item_path(params[:id]), method: "DELETE",class: "btn btn-danger", remote: true %>
<% end %>
</div>
<% end %>

fin_10_e-commerce_chatons/app/views/items/_add_cart_delete.html.erb
<%= form_with method: "PUT", url: cart_path  do |form| %>
  <%= form.select :quantity, [1, 2, 3, 4, 5]%>
  <%= form.submit "Ajouter au panier".html_safe, class:"btn btn-success"%>
  <%= link_to "<i class='fa fa-trash'></i>".html_safe, cart_path(params[:id]), method: "DELETE",class: "btn btn-danger", remote: true %>
<% end %>

fin_10_e-commerce_chatons/app/views/items/_del.html.erb
<%= link_to "<i class='fa fa-trash'></i>".html_safe, cart_path(item), method: "DELETE",class: "btn btn-danger", remote: true %>

fin_10_e-commerce_chatons/app/views/items/_update.html.erb
<div class="rate">
    <input type="radio" id="star5" name="rate" value="5" />
   <label for="star5" title="text">5 stars</label>
    <input type="radio" id="star4" name="rate" value="4" />
    <label for="star4" title="text">4 stars</label>
    <input type="radio" id="star3" name="rate" value="3" />
    <label for="star3" title="text">3 stars</label>
    <input type="radio" id="star2" name="rate" value="2" />
    <label for="star2" title="text">2 stars</label>
    <input type="radio" id="star1 é" name="rate" value="1" />
    <label for="star1" title="text">1 star</label>
 </div>

<p id="test">aaaaaaaaaaaaaaaaa</p>

fin_10_e-commerce_chatons/app/views/items/destroy.js.erb
$('#btn-cart').html("")
$('#btn-cart').html("<%= j render 'add_cart'%>")
$('#navbarTogglerDemo02').html("")
$('#navbarTogglerDemo02').html("<%= j render 'layouts/btn'%>")

fin_10_e-commerce_chatons/app/views/items/index.html.erb
<!-- Index -->
<div id="filter">
  <p id="all" class="btn btn-warning">All</p>
  <% @categories.each do |category| %>
  <p id=<%= category.name.split.join.downcase %> class="btn btn-success"><%= category.name %></p>
  <% end %>
<div>

<br>

<div class="row">

  <% @items.each do |item|%>
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100 <%= item.category.name.split.join.downcase %>">
        <%= image_tag item.picture, height: "200px;" %>
        <div class="card-body">
          
          <h4 class="card-title d-flex justify-content-between">
            <%= link_to item.title, item_path(item)%>
            <div>
            <% if @cart.is_in_cart?(item.id)%>
            <% else %>   
              <%= link_to '<i class="fas fa-cart-arrow-down"></i>'.html_safe, cart_url(item, 1), method: "PUT", remote: true, class: "btn btn-success", id:"go"%></a>
            <% end %>
            </div>
          </h4>
          <h5><%= item.price%>€        
          <% if item.item_average_rating != nil%>
          <small class="text-muted"><%= "★" * item.item_average_rating%></small>
          <% end %>
          </h5>
          <p class="card-text"><%= item.description%></p>
        </div>
        <div class="card-footer">

          <b><%= item.category.name %></b>
        </div>
      </div>
    </div>
  <%end%>

</div>


<script>

    $('a[id="go"]').click(function() {
      let text = $("#pill").text()
      let num = parseInt(text)
      $(this).hide()
      $("#pill").html(`${num + 1}`)
   });

<% @categories.each do |category| %>
  document.getElementById('<%= category.name.split.join.downcase %>').addEventListener('click', function(e){
        e.preventDefault;
        let index = document.querySelector('.row')
    for (let i = 0; i < index.children.length; i++) {
      if (!index.children[i].firstElementChild.classList.contains('<%= category.name.split.join.downcase %>')){
        index.children[i].style.display = "none"
      } else {
        index.children[i].style.display = "flex"
      }
    }
  });
<% end %>

document.getElementById('all').addEventListener('click', function(e){
      e.preventDefault;
      let index = document.querySelector('.row')
  for (let i = 0; i < index.children.length; i++) {
      index.children[i].style.display = "flex"
  }
});


</script>

fin_10_e-commerce_chatons/app/views/items/show.html.erb
    <br>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Home</li>
  </ol>
</nav>
<div class="card">
    <div class="row no-gutters">
        <div class="col-auto">
        <%= image_tag @item.picture, class:"img-fluid", width:"400px"%>
        </div>
        <div class="col">
        <div class="card-block px-2">
            <h4 class="card-title"><%= @item.title%></h4>
            <h5 class="card-title"><strong><%= @item.price%>€</strong></h5>
            <%= render 'rating/show', rate: @rate%>
            <p class="card-text"><%= @item.description%></p>
            <div id="btn-cart">
                <%= render 'add_cart', rate: @rate%>
            </div>
        </div>
    </div>
</div>
<div class="card-footer w-100 text-muted">
<b><%= @item.category.name %></b>
</div>
</div>
<div id="rating">
<%= render 'rating/rating', item: @item%>
</div>
<div class=>
<h2>Commentaires</h2>

<div>
  <%= render 'comments/index'%>
  <%= render 'comments/new'%>
</div>

<div class="toast" id="myToast">
    <div class="toast-header">
        <strong class="mr-auto"><i class="fa fa-grav"></i> We miss you!</strong>
        <small>11 mins ago</small>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
    </div>
    <div class="toast-body">
        It's been a long time since you visited us. We've something special for you. <a href="#">Click here!</a>
    </div>

fin_10_e-commerce_chatons/app/views/items/update.js.erb
$('#btn-cart').html("")
$('#btn-cart').html("<%= j render 'add_cart'%>")
$('#navbarTogglerDemo02').html("")
$('#navbarTogglerDemo02').html("<%= j render 'layouts/btn'%>")