7.3_eventbrite_clone_step3/config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  devise_for :users
  resources :users 
  resources :events do
    resource :attendances, only: [:create]
  end
  
end

7.3_eventbrite_clone_step3/app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :participation_send

  belongs_to :user
  belongs_to :event

  def participation_send
    UserMailer.participation_email(self).deliver_now
  end
end

7.3_eventbrite_clone_step3/app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, :duration, :title, :description, :price, :location, presence: true
  validates :title, length: {minimum: 5, maximum: 140}
  validates :description, length: {minimum: 20, maximum: 1000}
  validates :price, numericality: {greater_than: 0, less_than_or_equal_to: 1000}
  validate :multiple_of_five
  validate :cant_be_zero
  validate :cant_be_past
  belongs_to :admin, class_name: 'User'
  has_many :attendances
  has_many :users, through: :attendances


  def end_date
    self.start_date + (self.duration * 60)
  end

private 

  def multiple_of_five
    errors.add(:duration, "has to be a multiple of 5") unless duration % 5 == 0 
  end

  def cant_be_zero
    errors.add(:duration, "can't be 0") if duration == 0
  end

  def cant_be_past
    errors.add(:start_date, "can't be past") if start_date < Time.now
  end

end

7.3_eventbrite_clone_step3/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :events, foreign_key: 'admin_id', class_name: 'Event'
  has_many :attendances
  has_many :events, through: :attendances

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

7.3_eventbrite_clone_step3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation, :current_password)}
  end
end

7.3_eventbrite_clone_step3/app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def create
    # Amount in cents
    @event = Event.find(params[:event_id])

    @amount = @event.price * 100

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: "Inscription à #{@event.title}",
      currency: 'eur',
    })


    @guest = Attendance.create(stripe_customer_id: customer.id, user_id: current_user.id, event_id: @event.id)

    puts @guest.errors.full_messages
    redirect_to root_path


    rescue Stripe::CardError => e
    flash[:error] = e.message
    
  end

end

7.3_eventbrite_clone_step3/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @admin = User.find(@event.admin_id)
    @guests = @event.users
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :admin_id)
    end
end

7.3_eventbrite_clone_step3/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    redirect_to :root
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to '/users/edit'
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :encrypted_password, :description, :first_name, :last_name)
    end
end

7.3_eventbrite_clone_step3/app/helpers/attendances_helper.rb
module AttendancesHelper
end

7.3_eventbrite_clone_step3/app/helpers/events_helper.rb
module EventsHelper
end

7.3_eventbrite_clone_step3/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

7.3_eventbrite_clone_step3/app/helpers/users_helper.rb
module UsersHelper
end

7.3_eventbrite_clone_step3/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<br><br>

7.3_eventbrite_clone_step3/app/views/users/edit.html.erb
<main class="container">
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Voir le profil', @user, class:"btn btn-info" %> |
<%= link_to '« Retour Accueil', root_path, class:"btn btn-primary" %>
</main>

7.3_eventbrite_clone_step3/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>Description</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.description %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

7.3_eventbrite_clone_step3/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

7.3_eventbrite_clone_step3/app/views/users/show.html.erb
<main class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%if current_user.id == @user.id %>
  <%= link_to 'Editer le profil', edit_user_registration_path, class:"btn btn-success" %> |
  <%= link_to '« Retour Accueil', root_path, class:"btn btn-primary" %>
<% end %>

<h2 class="text-center">Les évènements organisés par <%=@user.first_name%></h2>

<% Event.all.each do |event| %>
  <% if @user.id == event.admin.id %>
    <div class="card my-3">
      <div class="card-header">
        <h4><%= event.title %></h4>
      </div>
      <div class="card-body">
        <h5 class="card-title">le <%= event.start_date %> à <%= event.location %></h5>
        <p class="card-text"><%= event.description %></p>
        <%= link_to 'Show', event, class:"btn btn-primary" %> 
        <% if user_signed_in? && current_user.id == event.admin.id %>
          <%= link_to 'Edit', edit_event_path(event), class:"btn btn-success" %> 
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        <% end %>
      </div>
      <div class="card-footer">
        Prix : <%= event.price %> € // Durée : <%= event.duration %> min
      </div>
    </div>
  <% end %>
<% end %>

</main>